name: 'Check E2E Coverage'
description: 'æ£€æŸ¥ E2E æµ‹è¯•è¦†ç›–çŽ‡å¹¶ç”ŸæˆæŠ¥å‘Š'

inputs:
  report-server-url:
    description: 'æŠ¥å‘ŠæœåŠ¡å™¨åœ°å€'
    required: true
    default: 'http://192.168.52.77:8080'

outputs:
  report_path:
    description: 'è¦†ç›–çŽ‡æŠ¥å‘Šæ–‡ä»¶è·¯å¾„'
    value: ${{ steps.coverage-report.outputs.report_path }}
  report_url:
    description: 'è¦†ç›–çŽ‡æŠ¥å‘Š URL'
    value: ${{ steps.report-url.outputs.report_url }}
  report_filename:
    description: 'è¦†ç›–çŽ‡æŠ¥å‘Šæ–‡ä»¶å'
    value: ${{ steps.report-url.outputs.report_filename }}
  markdown:
    description: 'Markdown æ ¼å¼çš„è¦†ç›–çŽ‡æ‘˜è¦'
    value: ${{ steps.coverage-report.outputs.markdown }}

runs:
  using: 'composite'
  steps:
    - name: Generate coverage report with Markdown
      id: coverage-report
      shell: bash
      run: npm run check:e2e-coverage:report -- --markdown
      continue-on-error: true
    
    - name: Generate coverage report URL
      if: always() && steps.coverage-report.outputs.report_path != ''
      id: report-url
      shell: bash
      run: |
        REPORT_FILE="${{ steps.coverage-report.outputs.report_path }}"
        REPORT_FILENAME=$(basename "$REPORT_FILE")
        
        # ç”ŸæˆæŠ¥å‘Š URLï¼ˆCI æœºå™¨ä¸Šçš„ http-server å·²åœ¨è¿è¡Œï¼‰
        REPORT_URL="${{ inputs.report-server-url }}/reports/$REPORT_FILENAME"
        echo "report_url=$REPORT_URL" >> $GITHUB_OUTPUT
        echo "report_filename=$REPORT_FILENAME" >> $GITHUB_OUTPUT
        
        echo "ðŸ“Š Coverage Report URL: $REPORT_URL"
        echo "ðŸ“„ Report file: $REPORT_FILE"

