name: 'Setup Configuration'
description: '获取配置项（支持从 GitHub Secrets 或本地 .user.json 读取）并设置环境变量'

inputs:
  http-proxy:
    description: 'HTTP 代理地址'
    required: false
    default: 'http://127.0.0.1:7890'
  https-proxy:
    description: 'HTTPS 代理地址'
    required: false
    default: 'http://127.0.0.1:7890'
  report-server-url:
    description: '报告服务器地址'
    required: false
    default: 'http://192.168.52.77:8080'
  github-token:
    description: 'GitHub Token (默认使用 GITHUB_TOKEN)'
    required: false
    default: ${{ github.token }}

outputs:
  FEISHU_WEBHOOK_URL:
    description: '飞书 Webhook URL'
    value: ${{ steps.get-feishu-url.outputs.FEISHU_WEBHOOK_URL }}
  PAT_TOKEN:
    description: 'GitHub Token (用于评论 PR)'
    value: ${{ inputs.github-token }}
  HTTP_PROXY:
    description: 'HTTP 代理地址'
    value: ${{ inputs.http-proxy }}
  HTTPS_PROXY:
    description: 'HTTPS 代理地址'
    value: ${{ inputs.https-proxy }}
  REPORT_SERVER_URL:
    description: '报告服务器地址'
    value: ${{ inputs.report-server-url }}

runs:
  using: 'composite'
  steps:
    - name: Setup environment variables
      shell: bash
      run: |
        echo "HTTP_PROXY=${{ inputs.http-proxy }}" >> $GITHUB_ENV
        echo "HTTPS_PROXY=${{ inputs.https-proxy }}" >> $GITHUB_ENV
        echo "REPORT_SERVER_URL=${{ inputs.report-server-url }}" >> $GITHUB_ENV
        echo "✅ Environment variables configured"
        echo "   HTTP_PROXY: ${{ inputs.http-proxy }}"
        echo "   HTTPS_PROXY: ${{ inputs.https-proxy }}"
        echo "   REPORT_SERVER_URL: ${{ inputs.report-server-url }}"
    
    - name: Get FEISHU_WEBHOOK_URL
      id: get-feishu-url
      shell: bash
      continue-on-error: true
      run: node .github/scripts/get-config.js FEISHU_WEBHOOK_URL
      env:
        FEISHU_WEBHOOK_URL: ${{ env.FEISHU_WEBHOOK_URL }}

